# Generated by Django 4.1.3 on 2022-11-10 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imeges',
            new_name='images',
        ),
    ]
